-- Generated by Ora2Pg, the Oracle database Schema converter, version 23.2
-- Copyright 2000-2022 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=oracle;sid=FREE;port=1521

SET client_encoding TO 'UTF8';


SET search_path = public,public;


CREATE TABLE fonds_table_all (
	material_name varchar(500),
	nom varchar(200),
	name1 varchar(500),
	data_size varchar(20),
	code varchar(100),
	jpeg_tiff varchar(100),
	code2 varchar(100),
	nrs varchar(10),
	generation varchar(20),
	author varchar(200),
	editor varchar(200),
	organization varchar(500),
	seria_name varchar(200),
	amount varchar(200),
	cab_num varchar(200),
	rack_num varchar(200),
	shelf varchar(200),
	vgb varchar(100),
	real_amount varchar(10),
	opis_num varchar(500),
	to_geolfond varchar(10),
	scale varchar(100),
	map_scale varchar(200),
	publish_year bigint,
	id bigint
) ;
